### ISSUE TITLE
people who have private keys and creds in their repos. add names to alert these people to fix their shit.

### ISSUE THREAD

**Issue by ocxo** [ocxo/wtf#1]
@challinan
@gomachan
@thechrisfischer

**Comment by ocxo** [comment]
@JohnFiedler
@ximus
@serdars
@HairyMezican
@zerdliu

**Comment by ocxo** [comment]
@jpd750
@mandrapola

**Comment by ocxo** [comment]
@pdam
@schowdhury
@8600100
@aschepis
@v1nc3ntlaw
@deanrobbins908

**Comment by ocxo** [comment]
@rrutia
@sdavies

oh god there are so many https://github.com/search?p=2&q=path%3A.ssh%2Fid_rsa&ref=searchresults&type=Code

![PicardDoubleFacepalm-1](https://f.cloud.github.com/assets/550256/91533/2e7e55ba-65a4-11e2-88f1-fcad23508381.jpg)

**Comment by sdavies** [comment]
Probably looking for:
https://github.com/search?q=path%3A.ssh%2Fid_rsa+PRIVATE&type=Code&ref=searchresults

Since those are the private keys.  The key in my repository is a public ssh key, which by definition.... is public.  :)

**Comment by ocxo** [comment]
more https://github.com/search?q=path%3A.ssh%2Fid_rsa+%22PRIVATE+KEY%22&type=Code&ref=searchresults
@tobinjt
@outan
@anjanavr47
@wistoch
@MichaelCPell
@54hotlover
@cyfex
@bobbydoap
@Gravian

**Comment by aschepis** [comment]
found it.. thanks for doing this.

**Comment by tobinjt** [comment]
Thanks for the heads up, but that key is passphrase protected.  Hopefully the other keys are too.
